In [1]:
import numpy as np
import torch

In [2]:
obs_history_buf = torch.zeros(1,1, 63, dtype=torch.float)
obs_history_buf

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [4]:
obs_buf_np = np.concatenate((np.random.rand(3), np.random.rand(3), np.random.rand(19), np.random.rand(19), np.random.rand(19) ))
obs_buf = torch.tensor(obs_buf_np,dtype=torch.float).unsqueeze(0)
print(obs_buf.shape)
obs_buf

torch.Size([1, 63])


tensor([[0.4419, 0.7969, 0.3946, 0.6650, 0.7351, 0.6843, 0.0379, 0.2359, 0.8286,
         0.0431, 0.9985, 0.1520, 0.5656, 0.3537, 0.6727, 0.4741, 0.5557, 0.5726,
         0.9501, 0.7463, 0.3448, 0.5579, 0.3419, 0.1771, 0.4275, 0.9605, 0.2686,
         0.2995, 0.3819, 0.6206, 0.1297, 0.8058, 0.2898, 0.4975, 0.6627, 0.8422,
         0.8943, 0.5860, 0.8672, 0.7402, 0.8684, 0.8877, 0.6206, 0.3838, 0.9516,
         0.1487, 0.1594, 0.1686, 0.8810, 0.3074, 0.7770, 0.3367, 0.6667, 0.1099,
         0.3193, 0.1854, 0.8109, 0.2394, 0.8122, 0.3449, 0.4165, 0.9988, 0.0136]])

In [5]:
obs_buf.unsqueeze(1).shape

torch.Size([1, 1, 63])

In [7]:
obs_history_buf = torch.cat([obs_history_buf[:, 1:],
                        obs_buf.unsqueeze(1)
                    ], dim=1)
obs_history_buf.shape

torch.Size([1, 1, 63])

In [9]:
policy = torch.load("policy_1.pt")
policy(obs_history_buf.detach())

c:\Users\yusuf\anaconda3\envs\ps\lib\site-packages\torch\serialization.py:1006: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  warnings.warn("'torch.load' received a zip file that looks like a TorchScript archive"


tensor([[[-0.1720,  0.3514,  0.1973,  0.6748,  7.0176, -2.3261, -0.9777,
           1.0318,  2.3761, 19.3268,  1.6664, -0.6357,  2.8770,  2.8615,
           2.6236,  0.5852,  0.9881,  0.8418,  0.2431]]],
       grad_fn=<ViewBackward0>)

In [3]:
import numpy as np

def get_middle_value(arr):
    if len(arr) % 2 == 0:
        raise ValueError("Array length must be odd")
    
    middle_index = len(arr) // 2
    return arr[middle_index]

# Example usage
array = np.array([-0.5, -0.4, -0.3, -0.2, -0.1 ,0 , 0.1 , 0.2, 0.3, 0.4, 0.5])
middle_value = array[len(array)//2]
print(f"The middle value is: {middle_value}")

The middle value is: 0.0
